# for other versions of docker-compose, check the official documentation
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    restart: always # Reiniciar sempre se houver falha
